project:
  type: website

website:
  title: "Dementia Demographics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: graphs.qmd
        text: Graphs
      - about.qmd
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



